// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbmmNxJNgYOSixYwyxekuLyqfJOR40dtQ',
    appId: '1:827529594727:web:b583a94a8393d761e2d1c2',
    messagingSenderId: '827529594727',
    projectId: 'consultorio-128e6',
    authDomain: 'consultorio-128e6.firebaseapp.com',
    storageBucket: 'consultorio-128e6.appspot.com',
    measurementId: 'G-760H5XW0ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC34TduLJehXdBYkibAHWoqk-QcnsP9pqI',
    appId: '1:827529594727:android:b96689cc96343775e2d1c2',
    messagingSenderId: '827529594727',
    projectId: 'consultorio-128e6',
    storageBucket: 'consultorio-128e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9uaTqcjZZoTDvt-5QKdXriOIGC0xpDZw',
    appId: '1:827529594727:ios:082246bfa5b95069e2d1c2',
    messagingSenderId: '827529594727',
    projectId: 'consultorio-128e6',
    storageBucket: 'consultorio-128e6.appspot.com',
    iosBundleId: 'com.example.consultorio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9uaTqcjZZoTDvt-5QKdXriOIGC0xpDZw',
    appId: '1:827529594727:ios:082246bfa5b95069e2d1c2',
    messagingSenderId: '827529594727',
    projectId: 'consultorio-128e6',
    storageBucket: 'consultorio-128e6.appspot.com',
    iosBundleId: 'com.example.consultorio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbmmNxJNgYOSixYwyxekuLyqfJOR40dtQ',
    appId: '1:827529594727:web:a03e02cc61ab27b4e2d1c2',
    messagingSenderId: '827529594727',
    projectId: 'consultorio-128e6',
    authDomain: 'consultorio-128e6.firebaseapp.com',
    storageBucket: 'consultorio-128e6.appspot.com',
    measurementId: 'G-N5LQD8F0FB',
  );
}
